account/urls.py
from django.urls import path
from . import views

app_name = "account"


urlpatterns = [
    path("", views.HomepageView.as_view(), name="homepage_view"),
    path("registration/", views.RegistrationView.as_view(), name="registration_view"),
    path("login/", views.LoginView.as_view(), name="login_view"),
    path("dashboard/", views.DashboardView.as_view(), name="dashboard_view"),
]

appointment/urls.py
from django.urls import path
from . import views

app_name = "appointment"

urlpatterns = [
    path("doctor/", views.DoctorListView.as_view(), name="doctor_list_view"),
    path('appointment/<str:id>/', views.AppointmentDetailView.as_view(), name='appointment_detail_view'),
    path('appointment-create/<str:doctor_id>/', views.AppointmentCreateView.as_view(), name='appointment_create_view'),
    # path('my-blog/', views.MyBlogListView.as_view(), name='my_blog_list_view'),

    path('ajax/load-time-slot/', views.loadTimeSlotView, name='load_time_slot_view'), # AJAX
]

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("blog/", views.BlogListView.as_view(), name="blog_list_view"),
    path('blog/<str:pk>/', views.BlogDetailView.as_view(), name='blog_detail_view'),
    path('blog-create/', views.BlogCreateView.as_view(), name='blog_create_view'),
    path('my-blog/', views.MyBlogListView.as_view(), name='my_blog_list_view'),
]

doctor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('blog.urls')),
    path('', include('appointment.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appointment/models.py
from django.db import models
from account.models import User
import datetime
from django.utils.translation import gettext as _

class Appointment(models.Model):

    TIME_SLOT_CHOICES = (
        ('1', '9:00 to 9:45'),
        ('2', '9:45 to 10:30'),
        ('3', '10:30 to 11:15'),
        ('4', '11:15 to 12:00'),
        ('5', '2:00 to 2:45'),
        ('6', '2:45 to 3:30'),
        ('7', '3:30 to 4:15'),
        ('8', '4:15 to 5:00'),
    )

    doctor = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'appointment_doctor')
    patient = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'appointment_patient')
    required_speciality = models.CharField(max_length=30)
    date = models.DateField()
    time_slot = models.CharField(max_length = 20, choices = TIME_SLOT_CHOICES )

    def __str__(self):
        return str(self.id)

templates/appointment_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}


<div class="container py-5">
        <h2>Appointment</h2>
        <br>
        <form method="POST" id="appointmentForm" data-time-slot-url="{% url 'appointment:load_time_slot_view' %}">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <button class="btn btn-primary" type="submit">Confirm</button>
        </form>
        {{doctor}}
</div>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
        $("#id_date").change(function () {
            const url = $("#appointmentForm").attr("data-time-slot-url");
            const date = $(this).val();  // get the selected date from the HTML input
            const doctor_id = '{{doctor_id}}'
            $.ajax({
                url: url,
                data: {
                    'date': date,
                    'doctor_id': doctor_id
                },
                success : function(data){

                    let html_data = '<option value="">---------</option>';
                    data.forEach(function (time_slot) {
                        html_data += `<option value="${time_slot[0]}">${time_slot[1]}</option>`
                    });
                    console.log(html_data);
                    $("#id_time_slot").html(html_data);
                }

                });
            });

    </script>

{% endblock %}

templates/appointment_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="container py-5">

            <h3>Doctor Name</h3>{{appointment.doctor.first_name}}&nbsp;{{appointment.doctor.last_name}}<br><br>
        <h3>Date</h3>{{appointment.date}}<br><br>
        <h3>Time</h3>{{appointment.get_time_slot_display}}<br><br>

</div>

{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

          <div class="container-fluid">

            <a class="navbar-brand" href="#">Navbar</a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">

                  <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                        <li class="nav-item">
                          <a class="nav-link active" aria-current="page" href="{% url 'account:homepage_view' %}">Home</a>
                        </li>

                        <li class="nav-item">
                          <a class="nav-link active" aria-current="page" href="{% url 'account:dashboard_view' %}">Dashboard</a>
                        </li>

                        <li class="nav-item">
                          <a class="nav-link active" aria-current="page" href="{% url 'blog:blog_list_view' %}">Blog</a>
                        </li>

                        {% if request.user.is_doctor == True %}

                            <li class="nav-item">
                              <a class="nav-link active" aria-current="page" href="{% url 'blog:blog_create_view' %}">Write Blog</a>
                            </li>

                            <li class="nav-item">
                              <a class="nav-link active" aria-current="page" href="{% url 'blog:my_blog_list_view' %}">My Blog</a>
                            </li>

                        {% endif %}

                        <li class="nav-item">
                          <a class="nav-link active" aria-current="page" href="{% url 'appointment:doctor_list_view' %}">Doctors</a>
                        </li>

                  </ul>

                </div>

          </div>

    </nav>
    {% block content %}


    {% endblock %}
  </body>
</html>

templates/blog_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}


<div class="container py-5">

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <button class="btn btn-primary" type="submit">Post</button>
        </form>

</div>

{% endblock %}

templates/blog_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="container py-5">

    <br>
        <p class="h5">{{blog.doctor_id}}</p>
        <blockquote class="blockquote">
        <p class="h2">{{blog.title}}</p><br>
        <footer class="blockquote-footer">by <cite title="Source Title">{{blog.author}}</cite></footer>
        </blockquote>
        <h3><span class="badge bg-light text-dark">{{blog.category}}</span></h3>
    <br>
        <div class="img w-50"> <img src="{% static blog.thumbnail.url %}"class="img-thumbnail"  alt="blog thumbnail">
        </div>
    <br>
        <p class="h5">{{blog.summary}}</p>
    <br>
        <div>{{blog.content}}
        </div>
</div>

{% endblock %}

templates/blog_list.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="container py-5">

        <div >
            <form method="GET" >
                {% csrf_token %}
                {{ form }}
                <button class="btn btn-primary" type="submit">Search</button>
            </form>
        </div>
        <br>
        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for blog in bloglist %}
                <div class="col m-3" style="width: 18rem;">
                    <div class="card" style="width: 18rem;">
                      <img class="card-img-top" src="{% static blog.thumbnail.url %}" alt="Card image cap">
                      <div class="card-body">
                        <h5 class="card-title">{{blog.title}}</h5>
                        <p class="card-text">{{blog.summary|truncatewords:15}}</p>
                        <a href="{% url 'blog:blog_detail_view' blog.id %}" class="btn btn-primary">Full Blog</a>
                      </div>
                    </div><br>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/dashboard.html
{% extends "base.html" %}
{% load static %}
{% block content %}
	
<div class="container py-5">

	{% if user.is_doctor %}
	  <h1>Doctor Dashboard</h1>
	{% endif %}

	{% if user.is_patient %}
	  <h1>Patient Dashboard</h1>
	{% endif %}

		<h2 style="color:MediumSeaGreen">User Info</h2>
		{% if user.profile_pic %}
		  <img src="{% static user.profile_pic.url %}" alt="profile" style="max-height:150px; max-width:150px;">
		{% endif %}

		{% if user_info.first_name %}
			<h4> FirstName :
				<span style="color:#990099">
					{{user_info.first_name}}
				</span>
			</h4>
		{% endif %}

		{% if user_info.last_name %}
			<h4> LastName :
				<span style="color:#990099">
					{{user_info.last_name}}
				</span>
			</h4>

		{% endif %}

		{% if user_info.username  %}
			<h4> Username :
				<span style="color:#990099">
					{{user_info.username}}
				</span>
			</h4>
		{% endif %}

		{% if user_info.email %}
			<h4> Email :
				<span style="color:#990099">
					{{user_info.email}}
				</span>
			</h4>
		{% endif %}

		{% if user_info.address.line1 %}
		<h2 style="color:MediumSeaGreen">address</h2>
			<h4> Line1 :
				<span style="color:#990099">
					{{user_info.address.line1}}
				</span>
			</h4>
		{% endif %}

		{% if user_info.address.city %}
			<h4> City :
				<span style="color:#990099">
					{{user_info.address.city}}
				</span>
			</h4>
		{% endif %}

		{% if user_info.address.state %}
			<h4> State :
				<span style="color:#990099">
					{{user_info.address.state}}
				</span>
			</h4>
		{% endif %}

		{% if user_info.address.pincode %}
			<h4> Pincode :
				<span style="color:#990099">
					{{user_info.address.pincode}}
				</span>
			</h4>
		{% endif %}

</div>

{% endblock %}

templates/doctor_list.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="container py-5">

        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for doctor in doctorlist %}
                <div class="col m-3" style="width: 18rem;">
                    <div class="card" style="width: 18rem;">
                      <img class="card-img-top" src="{% static doctor.profile_pic.url %}" alt="profile pic"><br>
                      <div class="card-body">
                        <h5 class="card-title">{{doctor.first_name}}&nbsp{{doctor.last_name}}</h5><br>
                        <a href="{% url 'appointment:appointment_create_view' doctor_id=doctor.id %}" class="btn btn-primary">Book Appointment</a>
                      </div>
                    </div><br>
                </div>
            {% endfor %}
        </div>

    </div>

{% endblock %}

templates/homepage.html
{% extends "base.html" %}

{% block content %}



<div class="container py-5">
    <a class="btn btn-primary" href="login" role="button">Login</a>
    <a class="btn btn-primary" href="registration" role="button">Registraion</a>
</div>

{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags %}


<!--Login-->
<div class="container py-5">

    <div >

        {% if login_form.non_field_errors %}
            {% for error in login_form.non_field_errors %}
            <div class="alert alert-danger">
                 <strong>{{ error|escape }}</strong>
            </div>
            {% endfor %}
        {% endif %}

    </div>

      <h1>Login</h1>
      <form method="POST">
        {% csrf_token %}
        <!-- {{ login_form|crispy }} -->
        {% for field in login_form %}
        <div class="fieldWrapper">
            {# uncomment to display field errors #}
            {# {{ field.errors }} #}

            {{ field|as_crispy_field }}
        </div>
        {% endfor %}
        <br>
        <button class="btn btn-primary" type="submit">Login</button>
      </form>
      <p class="text-center">Don't have an account? <a href="/registration">Create an account</a>.</p>
</div>

{% endblock %}

templates/my_blog.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="container py-5">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for blog in bloglist %}
            <div class="col m-3" style="width: 18rem;">
                <div class="card h-100" style="width: 18rem;">
                  <img class="card-img-top" src="{% static blog.thumbnail.url %}" alt="Card image cap">
                  <div class="card-body">
                    <h5 class="card-title">{{blog.title}}</h5>
                    <p class="card-text">{{blog.summary|truncatewords:15}}</p>
                    <a href="{% url 'blog:blog_detail_view' blog.id %}" class="btn btn-primary">Full Blog</a>
                  </div>
                </div><br>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/registration.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags %}

<!--Register-->
<div class="container py-5">
	<div>
		<!-- {% for message in messages %}
		<h3 style="color:red"> {{message}} </h3>
		{% endfor %} -->

		{% if registration_form.errors %}
	       {% for field in registration_form %}
	           {% for error in field.errors %}
	              <div class="alert alert-danger">
	                   <strong>{{ error|escape }}</strong>
	              </div>
	           {% endfor %}
	       {% endfor %}
	    {% endif %}
	</div>

	<h1>Registration</h1>
	<form method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{ registration_form|crispy }}
		<h3>Address</h3>
		{{ address_form|crispy }}
		<br>
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href="/login">login</a> instead.</p>


</div>

{% endblock %}